### ISSUE TITLE
multi file select

### ISSUE THREAD

**Issue by benjaminhoffman** [AlexanderWillner/imageoptim-alfred-workflow#1]
amazing!  i just googled for alfred imageoptim and found this.  i found a bunch of others and curious why'd you build this over the others that already exist?

anyway... is it possible to process a number of images at once? with alfred i can select a few images via file buffer (https://www.alfredapp.com/help/features/file-search/#file-buffer) but would be great to then shrink them as well. 

ty!

**Comment by AlexanderWillner** [comment]
Thanks, didn't use Alfred File Buffers in the past. Does version 1.2.0 work for you? The keyword is `imageoptim` followed by your search query. Then fill the buffer accordingly and press enter.

**Comment by benjaminhoffman** [comment]
Interesting. That's not my current flow (and `imageoptim` keyword didn't work for me -- but that may be a function of my setup since I'm new and struggling to get some setting configured)

What I do is:
- locate the file
- `option` + `->` 
- search `image...`
- click enter

then it processes the file.

I'm looking for a solution that can process multiple images at once.

More importantly, I want a workflow that will auto process each time a take a screenshot since I do that manually now.

i don't suppose either of those functions exist with your current solution and/or are easy to add?  I found a few other imageoptim solutions but yours looked the most up to date and simplest so started here.

**Comment by AlexanderWillner** [comment]
Will update the README - this is how I change multiple files at once:

* Option 1: open Finder, select a folder, press ⌘ +  ⌃ + Y (shortcut for [Universal Action](https://www.alfredapp.com/universal-actions/), typing "opt", select `Optimize Images`
* Option 2: open Finder, select a couple of images, press ⌘ +  ⌃ + Y (shortcut for [Universal Action](https://www.alfredapp.com/universal-actions/), typing "opt", select `Optimize Images`
* Option 3: invoke Alfred, type `imageoptim png`, select multiple files using ⌥ + Arrow up, press enter

**Comment by AlexanderWillner** [comment]
@benjaminhoffman does this work for you? btw: updated to version 1.3

**Comment by benjaminhoffman** [comment]
As a new Alfred user, I'm struggling to get it work but it I think it's user error. I'm going to continue to play with it. Ideally, one day, I'd like to get a workflow that auto processes screenshots, uploads them, and add them to my clipboard.

Thanks for the workflow @AlexanderWillner !  feel free to close this issue.

**Comment by AlexanderWillner** [comment]
* Using Alfred: I think this it is nice to see that everyone is using Alfred in a different way (I've updated the README to reflect the two ways how a user can invoke this workflow)
* Auto processing screenshots: I thinks this is what @vitorgalvao discussed in https://www.alfredforum.com/topic/17804-process-screenshots-w-imageoptim/ and implemented in #2 which was included in version 1.3
